<template>
  <div class="container">

    <h1>
      MiRNAs are short non-coding RNA molecules that act as post-transcriptional regulators of gene expression by base-paring with target mRNAs, playing a significant role in the regulation of various cellular functions. We collected datasets of bonafide miRNA-mRNA interactions generated by high-throughput experiments (e.g., CLASH, see Table below), and annotated each interaction with an interaction duplex and a set of features (e.g., duplex energy, duplex structure, target site composition, and target site context). Using these datasets, we generated powerful machine-learning (ML) models to promote the prediction of new interactions. Recognizing the need to introduce this valuable data and the powerful ML capabilities to the wider scientific community, we conceived this website as a welcoming and convenient hub for the research community. Our platform serves as a one-stop-shop, providing a comfortable space
    </h1>

  </div>
</template>



<script>
 
</script>

<style scoped>
.container {
  width: 90%;
  max-width: 900px;
  margin: 5vh auto;
  padding: 3vw;
  border: 0.3vw solid #ebebeb;
  background-color: rgba(244, 244, 244, 0.6);
  border-radius: 2vw;
  box-shadow: 0.5vw 0.5vw 1vw rgba(144, 143, 143, 0.5);
  display: flex;
  flex-direction: column;
  align-items: center;
  box-sizing: border-box; /* Ensures padding and border are included in the element's total width and height */
}

h1 {
  margin-bottom: 40px; /* Increase space below the title */
  text-align: center; /* Center-align the title */
}

</style>
